In [1]:
import numpy as np
import random

In [2]:
def simulate_prizedoor(n_sims):
    """
    Function
    --------
    simulate_prizedoor

    Parameters
    ----------
    n_sims : int
        The number of simulations to run

    Returns
    -------
    sims : array
        Random array of 0s, 1s, and 2s

    Example
    -------
    >>> print simulate_prizedoor(3)
    array([0, 0, 2])
    """
    return np.random.randint(0,3,(n_sims))
# num_of_simulations = 3
# simulate_prizedoor(num_of_simulations)

In [3]:
def simulate_guess(n_sims):
    """
    Function
    --------
    simulate_guess

    Parameters
    ----------
    n_sims : int
        The number of simulations to generate guesses for

    Returns
    -------
    guesses : array
        An array of guesses. Each guess is a 0, 1, or 2

    Example
    -------
    >>> print simulate_guess(5)
    array([0, 0, 0, 0, 0])
    """
    return np.random.randint(0,3,(n_sims))
# num_of_simulations = 3
#simulate_guess(num_of_simulations)

In [4]:
def goat_door(prizedoor,guesses):
    """
    Function
    --------
    goat_door

    Parameters
    ----------
    prizedoors : array
        The door that the prize is behind in each simulation
    guesses : array
        THe door that the contestant guessed in each simulation

    Returns
    -------
    goats : array
        The goat door that is opened for each simulation. Each item is 0, 1, or 2, and is different
        from both prizedoors and guesses

    Examples
    --------
    >>> print goat_door(np.array([0, 1, 2]), np.array([1, 1, 1]))
    >>> array([2, 2, 0])
    """
    goat_doors = []
    available = set([0,1,2]) # made into set to use set operations like {a,b}\{b} = {a}
    for i in range(len(prizedoor)):
        unavailable = set([prizedoor[i],guesses[i]])
        leftover = available - unavailable      
        door_to_show = list(leftover)[np.random.randint(0,len(leftover))] # if there's two options to choose from pick randomly
        goat_doors.append(door_to_show)
    return np.array(goat_doors)  
# num_of_simulations = 3
# p = simulate_prizedoor(num_of_simulations)
# g = simulate_guess(num_of_simulations)
# print(p,g,goat_door(p,g))

In [5]:
def switch_guess(guesses,goatdoor):
    """
    Function
    --------
    switch_guess

    The strategy that always switches a guess after the goat door is opened

    Parameters
    ----------
    guesses : array
         Array of original guesses, for each simulation
    goatdoors : array
         Array of revealed goat doors for each simulation

    Returns
    -------
    The new door after switching. Should be different from both guesses and goatdoors

    Examples
    --------
    >>> print switch_guess(np.array([0, 1, 2]), np.array([1, 2, 1]))
    >>> a
    """
    change = []
    available = set([0,1,2]) # made into set to use set operations like {a,b}\{b} = {a}
    for i in range(len(goatdoor)):
        unavailable = set([goatdoor[i],guesses[i]])
        leftover = available - unavailable        
        change.append(list(leftover)[0])
    return np.array(change) 
# num_of_simulations = 3
# p = simulate_prizedoor(num_of_simulations)
# g = simulate_guess(num_of_simulations)
# gd = goat_door(p,g)
# sg = switch_guess(g,gd)
# print("\n p",p,"\n g",g,"\ngd",gd,"\nsg",sg)

In [6]:
def win_percentage(guesses,prizedoors):
    """
    Function
    --------
    win_percentage

    Calculate the percent of times that a simulation of guesses is correct.

    Parameters
    -----------
    guesses : array
        Guesses for each simulation
    prizedoors : array
        Location of prize for each simulation

    Returns
    --------
    percentage : number between 0 and 100
        The win percentage

    Examples
    ---------
    >>> print win_percentage(np.array([0, 1, 2]), np.array([0, 0, 0]))
    33.333
    """
    sum_of_runs = len(guesses)
    wins = 0
    loss = 0
    for i in range(sum_of_runs):
        if guesses[i] == prizedoors[i]:
            wins += 1
        else:
            loss += 1
    win_perc = (wins/sum_of_runs)*100
    return (f"Win: {win_perc}%") 

In [8]:
def mh_sim(n_sims,print_simulation = False):
    prizedoors = simulate_prizedoor(n_sims)
    guessdoors = simulate_guess(n_sims)
    goatdoors = goat_door(prizedoors,guessdoors)
    swtichguessdoors = switch_guess(guessdoors,goatdoors)
    if print_simulation == True:
        print("\n       prizedoors:",prizedoors,
              "\n       guessdoors:",guessdoors,
              "\n        goatdoors:",goatdoors,
              "\n swtichguessdoors:",swtichguessdoors)
    else:
        None
    return win_percentage(swtichguessdoors,prizedoors)    

In [9]:
mh_sim(5000)

'Win: 66.28%'

In [10]:
for i in range(0,100,5):
    print(mh_sim(5000))

Win: 65.10000000000001%
Win: 66.2%
Win: 66.47999999999999%
Win: 67.58%
Win: 67.12%
Win: 66.0%
Win: 65.62%
Win: 65.08%
Win: 66.46%
Win: 67.4%
Win: 66.10000000000001%
Win: 66.22%
Win: 66.5%
Win: 67.80000000000001%
Win: 66.60000000000001%
Win: 66.03999999999999%
Win: 67.24%
Win: 67.0%
Win: 67.0%
Win: 66.62%
